name: Secrets and Environment Variables

on:
  push:
    branches:
      - main

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Access Repository Secrets
        env:
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

        run: |
          echo "Spotipy Redirect URI: $SPOTIPY_REDIRECT_URI"
          echo "Spotipy Client Secret: $SPOTIPY_CLIENT_SECRET"
          echo "Spotipy Client ID: $SPOTIPY_CLIENT_ID"
          echo "Secret Key: $SECRET_KEY"
