name: Secrets and Environment Variables
on: push

jobs:
  runs-on: ubuntu-latest
  env:
    SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
    SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
    SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
